Add an option to flush span info during updates to avoid OutOfBounds crashes
Summary:
**Background**
We've run into a crash where when modifying items near the edge of the viewport, where we get an OutOfBounds error due to `StaggeredGridLayoutManager` attempting to invalidate the span information of `mData` based on values beyond its range because `mFullSpanItems` indices are beyond the end of them. It's not yet clear to me when this drift out of sync happens, but it's not clear to me that Litho is interfacing with the layout wrong in any way.

**Crash**
```
java.lang.ArrayIndexOutOfBoundsException: start < 0 || end > len. start=19, end=23, len=22
  	at java.util.Arrays.checkStartAndEnd(Arrays.java:1732)
  	at java.util.Arrays.fill(Arrays.java:803)
  	at androidx.recyclerview.widget.StaggeredGridLayoutManager$LazySpanLookup.invalidateAfter(StaggeredGridLayoutManager.java:2878)
  	at androidx.recyclerview.widget.StaggeredGridLayoutManager.handleUpdate(StaggeredGridLayoutManager.java:1550)
  	at androidx.recyclerview.widget.RecyclerView$LayoutManager.onItemsAdded(Unknown Source)
  	at androidx.recyclerview.widget.RecyclerView$6.dispatchUpdate(RecyclerView.java:1007)
  	at androidx.recyclerview.widget.RecyclerView$6.onDispatchSecondPass(RecyclerView.java:1024)
  	at androidx.recyclerview.widget.AdapterHelper.consumePostponedUpdates(AdapterHelper.java:121)
  	at androidx.recyclerview.widget.AdapterHelper.consumeUpdatesInOnePass(AdapterHelper.java:557)
  	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3956)
  	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3685)
  	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1885)
  	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:408)
    ...
```

**In-Depth**
- StaggeredGridLayoutManager attempts to save span recalculation effort by invalidating the items after the last position being modified, up to the next full span item (`FSI` in code).
- This is because full span items act as a "reset" or division point for the span calculation, since afterwards you always start at 0.
- In our crash case, we can see [`StaggeredGridLayoutManager.LazySpanLookup.invalidateAfter()`](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/recyclerview/recyclerview/src/main/java/androidx/recyclerview/widget/StaggeredGridLayoutManager.java?source=post_page---------------------------%2F&autodive=0%2F#1512) returning a position >= length of `mData` and then it further gets incremented before being passed in to `Arrays.fill()`.
  - The return value of `invalidateAfter()` is the last FSI it invalidated, thereby returning the range of invalidated regular items up to the next "full width separator" / FSI.
  - It never gets checked for length, which is dangerous unto itself.

**A Solution**
Note that it doesn't say *the* solution lol.

- There's a [less-efficient alternate codepath](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/recyclerview/recyclerview/src/main/java/androidx/recyclerview/widget/StaggeredGridLayoutManager.java?source=post_page---------------------------%2F&autodive=0%2F#2871) where no full span items are found which we can force that avoids doing any specific sub-range `fill()'ing.
- It only occurs when FSIs are empty. We can force this by wiping them out ahead of any mutations.

As a result, performance is reduced on these mutations of the items, but for our use case, it's not a big deal.

**Changes**
- Add a new constructor for a variant of StaggeredGridLayoutInfo that propogates the eager invalidation to Litho's StaggeredGridLayoutManager subclass
  - Default to false
- Upon receiving an `onItems_____()`, we call `onItemsChanged()`
  - Alternatively, `invalidateSpanAssignments()` works identically.
  - However, it seems like `onItemsChanged()` may be the better semantic thing to call, and it currently is never called.
  - It's not clear who should be calling it, however, and the docs are vague and mentions on the internet are scarce.

This resolves the crash scenario, though not in an ideally performant way. For a recycler view not being updated all that frequently, I think this is an acceptable short- to mid-term fix, though.

Reviewed By: muraziz

Differential Revision: D17897788

fbshipit-source-id: 4e7652a5447ad25ae5cc57b32504e791fa256fd1