Remove depreacated method usage of AnnotationHolder in graphql and litho plugins
Summary:
```
#c.i.c.d.i.AnnotationHolderImpl - 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class com.facebook.litho.intellij.inspections.MethodCallAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation(...).create()` instead [Plugin: com.facebook.litho.intellij]
com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class com.facebook.litho.intellij.inspections.MethodCallAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation(...).create()` instead [Plugin: com.facebook.litho.intellij]
```

Reviewed By: jselbo

Differential Revision: D47658767

fbshipit-source-id: 018e489f96df38c115e17b7a7ace83071298ee99