Bump Robolectric to 4.9 on Gradle
Summary:
- Bumping Gradle version of robolectric to 4.9
- This requires us to add a new `robolectric.jar` files as when I didn't I had errors like the following in the `litho-oss` task:

```
    java.lang.IllegalArgumentException: Path is not a file: /data/sandcastle/boxes/eden-trunk-hg-fb4a-fbsource/fbandroid/libraries/components/lib/fb/android-all/android-all-instrumented-13-robolectric-9030017-i4.jar
```

I'm cleaning up the old jar files in a diff up in this stack (D43499594)

allow-large-files

Reviewed By: pentiumao

Differential Revision: D43497422

fbshipit-source-id: 3cc833efebe6c438186f7e505cc48e8a1fb7adee