Fix broken test fbsource//fbandroid/libraries/components/litho-it/src/test/com/facebook/litho/specmodels:specmodels
Summary:
Fix missing some javax.lang classes

```
Failed to execute isolated step <javac>
: warning: unknown enum constant kotlin.annotations.jvm.MigrationStatus.STRICT

  reason: class file for kotlin.annotations.jvm.MigrationStatus not found
fbandroid/libraries/components/litho-it/src/test/com/facebook/litho/specmodels/generator/JavadocGeneratorTest.java:74: error: cannot access javax.lang.model.type.TypeMirror
            .specTypeName(ClassName.get(TypeSpecDataHolder.class))
                                   ^
```

Found we use provided_deps in [KSP processors ](https://www.internalfb.com/code/fbsource/[b065090f62ad]/fbandroid/java/com/facebook/annotationprocessors/injectwithprovider/ksp/BUCK) where the stub jar have the classes definition.

Reviewed By: navidqar

Differential Revision: D75964358

fbshipit-source-id: 59e2d90466f3883915b850c1a5ffaaebedf97bca