Fix crash caused by SnapHelper
Summary:
A crash happened when I play the lithography sample
* Click the favourite button of the item who has a SnapHelper
* Move the item off screen
* Move it back
```java
 java.lang.IllegalStateException: An instance of OnFlingListener already set.
     at android.support.v7.widget.SnapHelper.setupCallbacks(SnapHelper.java:114)
     at android.support.v7.widget.SnapHelper.attachToRecyclerView(SnapHelper.java:102)
     at com.facebook.litho.widget.RecyclerSpec.onMount(RecyclerSpec.java:163)
     at com.facebook.litho.widget.Recycler.onMount(Recycler.java:121)
     at com.facebook.litho.ComponentLifecycle.mount(ComponentLifecycle.java:183)
     at com.facebook.litho.MountState.mountLayoutOutput(MountState.java:994)
     at com.facebook.litho.MountState.mount(MountState.java:217)
     at com.facebook.litho.LithoView.mount(LithoView.java:563)
     at com.facebook.litho.ComponentTree.mountComponent(ComponentTree.java:476)
     at com.facebook.litho.LithoView.performIncrementalMount(LithoView.java:508)
     at com.facebook.litho.LithoView.maybePerformIncrementalMountOnView(LithoView.java:478)
     at com.facebook.litho.LithoView.offsetTopAndBottom(LithoView.java:416)
     at android.support.v7.widget.RecyclerView.offsetChildrenVertical(RecyclerView.java:4489)
     at android.support.v7.widget.RecyclerView$LayoutManager.offsetChildrenVertical(RecyclerView.java:8389)
     at android.support.v7.widget.OrientationHelper$2.offsetChildren(OrientationHelper.java:362)
     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)
     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1061)
     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4726)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
     at android.view.Choreographer.doFrame(Choreographer.java:618)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
     at android.os.Handler.handleCallback(Handler.java:751)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6119)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
I find out that after changing the state of favourited the mRecyclerView of SnapHelper become null, so when `snapHelper.attachToRecyclerView(null);` evaluate, it just skip `destroyCallbacks();`
Then I follow the code and find that in `FeedItemComponentSpec.java`. Every time the Recycler create, it pass a new PagerSnapHelper() and in `RecyclerSpec.java` the shouldUpdate method does not return true when snapHelper changed.

This PR just fix that crash
Closes https://github.com/facebook/litho/pull/233

Differential Revision: D5745189

Pulled By: pasqualeanatriello

fbshipit-source-id: c411bf4c6d1e3eb09568bf09963bb78fc8866167