explicit type casting needed (#569)
Summary:
Type casting is required otherwise there is an error message from the complier: ```error: incompatible types: List<integer> cannot be converted to List<Object>```

<!-- Thanks for submitting a pull request! We appreciate you taking the time to work on these
changes. Please provide enough information so that others can review your pull request. The three
fields below are mandatory. -->

<!-- Explain the **motivation** for making this change. What existing problem does the pull request
solve? -->

## Changelog

<!-- Help reviewers and the release process by writing your own changelog entry. This should just be
a brief oneline we can mention in our release notes: https://github.com/facebook/litho/releases -->
Pull Request resolved: https://github.com/facebook/litho/pull/569

Test Plan:
<!-- Demonstrate the code is solid. Example: The exact commands you ran and their output, output of
the test runner and how you invoked it (you've added tests, right?), screenshots/videos if the pull
request changes UI. -->

Reviewed By: muraziz

Differential Revision: D16402182

Pulled By: astreet

fbshipit-source-id: ef57d7e73f825dce067f7e84eb4b41c0c3bc5417