Fix ViewPredicate drawable helper for robo 3.3
Summary:
With newer SDKs, View#onDraw is no longer public, so we need to go through the
declared methods to make this work.

This is backwards-compatible with 3.0 which we is still used internally.

Previously, you'd see this with 3.3:
```
FAILURE com.facebook.litho.testing.viewtree.ViewPredicatesTest testHasDrawable: java.lang.NoSuchMethodException: android.view.View.onDraw(android.view.View)
java.lang.RuntimeException: java.lang.NoSuchMethodException: android.view.View.onDraw(android.view.View)
        at com.facebook.litho.testing.viewtree.ViewPredicates.getDrawnViewDescription(ViewPredicates.java:225)
        at com.facebook.litho.testing.viewtree.ViewPredicates.access$100(ViewPredicates.java:38)
        at com.facebook.litho.testing.viewtree.ViewPredicates$6.apply(ViewPredicates.java:187)
        at com.facebook.litho.testing.viewtree.ViewPredicates$6.apply(ViewPredicates.java:170)
        at com.facebook.litho.testing.viewtree.ViewPredicatesTest.testHasDrawable(ViewPredicatesTest.java:155)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:488)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
        at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
        at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
```

Reviewed By: IanChilds

Differential Revision: D5051929

fbshipit-source-id: 7baa847a338be1a5c9fa0846c475ad699a11b341